### ISSUE TITLE
Using version 5 of Vega-Lite in idyll?

### ISSUE THREAD

**Issue by penpenLoveUwU** [idyll-lang/idyll-vega-lite#14]
Hi, I am currently not able to use some Vega-Lite v5 features like Parameter in idyll. I wonder if this is because we are still using "vega-lite": "^4.0.0" in package.json. If possible, could you please update vega-lite to version 5? Thanks so so so much!

**Comment by mathisonian** [comment]
Hi @penpenLoveUwU - this is fixed in the latest release on npm (`idyll-vega-lite@3`) -- sorry for the delay!
